file_format: "1"
id: aquila
name: Aquila/Sweep
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - aquila_left
  - aquila_right
