file_format: "1"
id: aquila
name: Aquila
type: shield
url: https://github.com/AdamClements/zmk-aquila
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - aquila_left
  - aquila_right
